[2022-03-16 20:23:56,933] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_song_feat_v02.extract_from_zip_task scheduled__2022-03-16T00:00:00+00:00 [queued]>
[2022-03-16 20:23:56,940] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_song_feat_v02.extract_from_zip_task scheduled__2022-03-16T00:00:00+00:00 [queued]>
[2022-03-16 20:23:56,940] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 20:23:56,940] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-03-16 20:23:56,940] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 20:23:56,947] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_from_zip_task> on 2022-03-16 00:00:00+00:00
[2022-03-16 20:23:56,952] {standard_task_runner.py:52} INFO - Started process 9390 to run task
[2022-03-16 20:23:56,954] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_song_feat_v02', 'extract_from_zip_task', 'scheduled__2022-03-16T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_song_feat_v02.py', '--cfg-path', '/tmp/tmp09_ddgwz', '--error-file', '/tmp/tmpd5hfxl_7']
[2022-03-16 20:23:56,955] {standard_task_runner.py:77} INFO - Job 109: Subtask extract_from_zip_task
[2022-03-16 20:23:56,985] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_song_feat_v02.extract_from_zip_task scheduled__2022-03-16T00:00:00+00:00 [running]> on host 56c17fb3521b
[2022-03-16 20:23:57,016] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_ingestion_dag_song_feat_v02
AIRFLOW_CTX_TASK_ID=extract_from_zip_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-16T00:00:00+00:00
[2022-03-16 20:23:57,017] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_song_feat_v02.py", line 28, in extract_from_zip
    zipObj.extract(path_to_file)
  File "/usr/local/lib/python3.7/zipfile.py", line 1619, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python3.7/zipfile.py", line 1658, in _extract_member
    member = self.getinfo(member)
  File "/usr/local/lib/python3.7/zipfile.py", line 1431, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'musicoset_songfeatures.zip/musicoset_songfeatures/acoustic_features.csv' in the archive"
[2022-03-16 20:23:57,026] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_ingestion_dag_song_feat_v02, task_id=extract_from_zip_task, execution_date=20220316T000000, start_date=20220316T202356, end_date=20220316T202357
[2022-03-16 20:23:57,034] {standard_task_runner.py:92} ERROR - Failed to execute job 109 for task extract_from_zip_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_song_feat_v02.py", line 28, in extract_from_zip
    zipObj.extract(path_to_file)
  File "/usr/local/lib/python3.7/zipfile.py", line 1619, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python3.7/zipfile.py", line 1658, in _extract_member
    member = self.getinfo(member)
  File "/usr/local/lib/python3.7/zipfile.py", line 1431, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'musicoset_songfeatures.zip/musicoset_songfeatures/acoustic_features.csv' in the archive"
[2022-03-16 20:23:57,046] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 20:23:57,070] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
