[2022-03-16 19:20:03,684] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_song_feat.format_to_parquet_task scheduled__2022-03-16T00:00:00+00:00 [queued]>
[2022-03-16 19:20:03,690] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_song_feat.format_to_parquet_task scheduled__2022-03-16T00:00:00+00:00 [queued]>
[2022-03-16 19:20:03,691] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 19:20:03,691] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-16 19:20:03,691] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 19:20:03,698] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-03-16 00:00:00+00:00
[2022-03-16 19:20:03,702] {standard_task_runner.py:52} INFO - Started process 6335 to run task
[2022-03-16 19:20:03,704] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_song_feat', 'format_to_parquet_task', 'scheduled__2022-03-16T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_song_feat.py', '--cfg-path', '/tmp/tmp0k1vm_79', '--error-file', '/tmp/tmp41jrdbk8']
[2022-03-16 19:20:03,705] {standard_task_runner.py:77} INFO - Job 98: Subtask format_to_parquet_task
[2022-03-16 19:20:03,735] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_song_feat.format_to_parquet_task scheduled__2022-03-16T00:00:00+00:00 [running]> on host 56c17fb3521b
[2022-03-16 19:20:03,765] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_ingestion_dag_song_feat
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-16T00:00:00+00:00
[2022-03-16 19:20:03,766] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_song_feat.py", line 29, in format_to_parquet
    table = pj.read_csv(src_file)
NameError: name 'pj' is not defined
[2022-03-16 19:20:03,774] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_ingestion_dag_song_feat, task_id=format_to_parquet_task, execution_date=20220316T000000, start_date=20220316T192003, end_date=20220316T192003
[2022-03-16 19:20:03,782] {standard_task_runner.py:92} ERROR - Failed to execute job 98 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_song_feat.py", line 29, in format_to_parquet
    table = pj.read_csv(src_file)
NameError: name 'pj' is not defined
[2022-03-16 19:20:03,796] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 19:20:03,818] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
