[2022-03-15 18:59:34,979] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v02.format_to_parquet_task scheduled__2020-10-01T00:00:00+00:00 [queued]>
[2022-03-15 18:59:34,986] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v02.format_to_parquet_task scheduled__2020-10-01T00:00:00+00:00 [queued]>
[2022-03-15 18:59:34,986] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 18:59:34,986] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-03-15 18:59:34,986] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 18:59:34,993] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2020-10-01 00:00:00+00:00
[2022-03-15 18:59:34,998] {standard_task_runner.py:52} INFO - Started process 3311 to run task
[2022-03-15 18:59:35,000] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_v02', 'format_to_parquet_task', 'scheduled__2020-10-01T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_v02.py', '--cfg-path', '/tmp/tmp_42ct_86', '--error-file', '/tmp/tmp0mt4k2u_']
[2022-03-15 18:59:35,001] {standard_task_runner.py:77} INFO - Job 43: Subtask format_to_parquet_task
[2022-03-15 18:59:35,034] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_v02.format_to_parquet_task scheduled__2020-10-01T00:00:00+00:00 [running]> on host 3570d6d4f2dc
[2022-03-15 18:59:35,056] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-15 18:59:35,066] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_ingestion_dag_v02
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2020-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-10-01T00:00:00+00:00
[2022-03-15 18:59:35,067] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 32, in format_to_parquet
    table = pj.read_json(src_file)
  File "pyarrow/_json.pyx", line 237, in pyarrow._json.read_json
  File "pyarrow/_json.pyx", line 192, in pyarrow._json._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/albums-full-info-10.json'. Detail: [errno 2] No such file or directory
[2022-03-15 18:59:35,075] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_ingestion_dag_v02, task_id=format_to_parquet_task, execution_date=20201001T000000, start_date=20220315T185934, end_date=20220315T185935
[2022-03-15 18:59:35,083] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_v02.py", line 32, in format_to_parquet
    table = pj.read_json(src_file)
  File "pyarrow/_json.pyx", line 237, in pyarrow._json.read_json
  File "pyarrow/_json.pyx", line 192, in pyarrow._json._get_reader
  File "pyarrow/io.pxi", line 1551, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1522, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 886, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 896, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/albums-full-info-10.json'. Detail: [errno 2] No such file or directory
[2022-03-15 18:59:35,092] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 18:59:35,117] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
