[2022-03-15 21:01:17,640] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v02.extract_from_zip_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-15 21:01:17,647] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v02.extract_from_zip_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-15 21:01:17,648] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 21:01:17,648] {taskinstance.py:1239} INFO - Starting attempt 9 of 9
[2022-03-15 21:01:17,648] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 21:01:17,655] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): extract_from_zip_task> on 2020-01-01 00:00:00+00:00
[2022-03-15 21:01:17,660] {standard_task_runner.py:52} INFO - Started process 6689 to run task
[2022-03-15 21:01:17,662] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_v02', 'extract_from_zip_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_v02.py', '--cfg-path', '/tmp/tmpwl28uc2q', '--error-file', '/tmp/tmptukgs0iy']
[2022-03-15 21:01:17,662] {standard_task_runner.py:77} INFO - Job 65: Subtask extract_from_zip_task
[2022-03-15 21:01:17,695] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_v02.extract_from_zip_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 3570d6d4f2dc
[2022-03-15 21:01:17,717] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1110, in render_template
    template = jinja_env.from_string(content)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'regex_replace'.
[2022-03-15 21:01:17,725] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_ingestion_dag_v02, task_id=extract_from_zip_task, execution_date=20200101T000000, start_date=20220315T210117, end_date=20220315T210117
[2022-03-15 21:01:17,734] {standard_task_runner.py:92} ERROR - Failed to execute job 65 for task extract_from_zip_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1418, in _execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1992, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1061, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1074, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1110, in render_template
    template = jinja_env.from_string(content)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'regex_replace'.
[2022-03-15 21:01:17,753] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 21:01:17,780] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
