[2022-03-16 18:14:43,492] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v04_pt2.format_to_parquet_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-03-16 18:14:43,499] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_ingestion_dag_v04_pt2.format_to_parquet_task scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2022-03-16 18:14:43,499] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 18:14:43,499] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-16 18:14:43,499] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 18:14:43,506] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2020-04-01 00:00:00+00:00
[2022-03-16 18:14:43,510] {standard_task_runner.py:52} INFO - Started process 3265 to run task
[2022-03-16 18:14:43,511] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_ingestion_dag_v04_pt2', 'format_to_parquet_task', 'scheduled__2020-04-01T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/gcs_ingestion_dag_v04_pt2.py', '--cfg-path', '/tmp/tmpir4ftm9_', '--error-file', '/tmp/tmp8jv93t40']
[2022-03-16 18:14:43,512] {standard_task_runner.py:77} INFO - Job 93: Subtask format_to_parquet_task
[2022-03-16 18:14:43,544] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_ingestion_dag_v04_pt2.format_to_parquet_task scheduled__2020-04-01T00:00:00+00:00 [running]> on host 56c17fb3521b
[2022-03-16 18:14:43,566] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-16 18:14:43,578] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_ingestion_dag_v04_pt2
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2022-03-16 18:14:45,846] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_v04_pt2.py", line 29, in format_to_parquet
    table = pj.read_json(src_file, read_options=ro)
  File "pyarrow/_json.pyx", line 246, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Column() changed from object to string in row 0
[2022-03-16 18:14:45,855] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_ingestion_dag_v04_pt2, task_id=format_to_parquet_task, execution_date=20200401T000000, start_date=20220316T181443, end_date=20220316T181445
[2022-03-16 18:14:45,865] {standard_task_runner.py:92} ERROR - Failed to execute job 93 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_ingestion_dag_v04_pt2.py", line 29, in format_to_parquet
    table = pj.read_json(src_file, read_options=ro)
  File "pyarrow/_json.pyx", line 246, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Column() changed from object to string in row 0
[2022-03-16 18:14:45,888] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 18:14:45,921] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
